### ISSUE TITLE
Missing .gitmodules

### ISSUE THREAD

**Issue by KhoraLee** [silvershort/nendoroidList#33]
2e455f1f68c06375d52fa7ee131d0294e8d39262 커밋에 . gitmodules 파일이 누락되어 submodule을 init할 수 없는 문제가 있음.

**Comment by silvershort** [comment]
해당 커밋에 의도치않게 웹버전 폴더가 같이 커밋이 되버린 것 같네요...
실수로 커밋해버린거긴한데 이참에 서브모듈에 대한 개념을 좀 익히는것도 좋을것같아서 관련 내용을 좀 찾아본 후에 .gitmodules 파일을 올려보도록 하겠습니다.
