### ISSUE TITLE
DB 업데이트에 실패하는 현상

### ISSUE THREAD

**Issue by KhoraLee** [silvershort/nendoroidList#52]
최근에 파서를 다시 작성하면서 DB 자체를 Rebuild하면서 DB 파일 전체가 변경되는 커밋이 하나 발생했습니다.(https://github.com/KhoraLee/NendoroidDB/commit/9237c59d57c5d58c395a6a27827bacb899390785).

깃헙 commit diff api가 변경된 파일 리스트를 불러올때 최대 300개의 파일만 불러오면서 업데이트에 성공했으나 기존 DB와 동일한것처럼 표시되는 현상이 발생한것입니다. (https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit)
단일 commit 정보를 불러오는 api에서는 변경된 파일 리스트를 300개씩 총 3천개를 볼수 있으나 commit diff에서는 변경된 파일을 300개 이후로 불러올 수 있는 방법이 없어보입니다. 

GitHub API가 개선되지 않는 이상 git patch나 diff파일([.patch](https://github.com/KhoraLee/NendoroidDB/compare/3740f6dd6d8606916d78187617d79b2c7d2e203b...deb6bb080f994dd11e6d46941099eb0f8cc624bb.patch) / [.diff](https://github.com/KhoraLee/NendoroidDB/compare/3740f6dd6d8606916d78187617d79b2c7d2e203b...deb6bb080f994dd11e6d46941099eb0f8cc624bb.diff))을 읽어서 변경된 파일리스트를 파싱하거나 그냥 수동으로 DB전체를 다시 다운받는 버튼을 추가하는게 좋아보입니다.

**Comment by silvershort** [comment]
갑자기 업데이트가 안되는게 그런 문제가 있었군요...

현재 앱 설치 후 최초 데이터 다운로드 속도를 올리기 위해서 Firebase의 저장소인 Cloud FireStore에 모든 넨도 데이터를 수동으로 업로드해두고 최초 다운로드는 거기서 하도록 설정 해두었는데요.
일단은 임시 방편으로 DB 업데이트도 Cloud FireStore 에서 하도록 앱 업데이트를 진행 할 예정입니다.

사용자가 데이터를 Github쪽에서 직접 받는건 이제 슬슬 한계가 왔다고 느끼는 중입니다.
아무리 최적화를 하더라도 받는 데이터에 비해서 너무나도 속도가 느리고, API의 제약으로 데이터를 효율적으로 받기가 어렵고 또 무료 API 호출횟수 소진시 403에러가 뜨는문제도 있습니다.

현재 적용중인 Cloud FireStore를 이용하면 이를 해결 할 수 있지만 이를 활용하려면
DB업데이트가 되면 -> 그걸 확인하고 수동으로 예전 방식으로 전체 데이터 다운로드 -> 관리자계정으로 앱내에서 Cloud FireStore 업로드
이런 과정을 거쳐야하기 때문에 언제까지나 계속 이 방식을 사용할 순 없고, 위의 프로세스를 어떻게 자동화 시켜야할지 고민중에 있네요...

무튼 이슈 올려주셔서 감사합니다! 혹시라도 조금 더 개선된 방법으로 DB를 제공해주실 수 있는 좋은 방법이 있으시다면 개선 부탁드리겠습니다! 다만 이 앱은 광고가 없는 수익 제로의 앱이기 때문에... 언제까지나 운영비용이 들지 않는 선에서 가능한게 있다면요...

**Comment by silvershort** [comment]
https://github.com/silvershort/nendoroidList/commit/a19a23f82a1c2717dced184a68321872e132dafe 에서 수정
